# Generated by Django 3.0.7 on 2020-07-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionXYZ_app', '0005_product_dprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dprice',
        ),
    ]
