# Generated by Django 3.0.7 on 2020-07-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionXYZ_app', '0008_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
