# Generated by Django 3.0.7 on 2020-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionXYZ_app', '0009_auto_20200716_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
