# Generated by Django 3.0.7 on 2020-07-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FashionXYZ_app', '0010_auto_20200716_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
